"""
Thin bridge — re-exports Smart Token Prod SDK for this project.

Generated by `smart-token integrate`. Prefer importing from here so the host
does not need PYTHONPATH=vendor hacks.

    from smart_token_bridge import protect_artifact, open_artifact, status
"""

from smart_token_prod.sdk import (  # noqa: F401
    artifact_friction_status,
    is_available,
    open_artifact,
    protect_artifact,
    repair_artifact_mac,
    status,
)

__all__ = [
    "is_available",
    "status",
    "protect_artifact",
    "open_artifact",
    "artifact_friction_status",
    "repair_artifact_mac",
]
